# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf5RHRb58gzRwzQG4CKuC8tZ3HAlStb4
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import count, avg, max, min, sum, desc
import pandas as pd
import kagglehub
import os

# Create Spark Session
spark = SparkSession.builder.appName("BigDataAnalysis").getOrCreate()

# Download dataset from Kaggle
path = kagglehub.dataset_download("mohammadtalib786/retail-sales-dataset")

print("Dataset downloaded to:", path)

# Find CSV file in downloaded folder
csv_files = [f for f in os.listdir(path) if f.endswith(".csv")]

if not csv_files:
    raise FileNotFoundError("No CSV file found in the downloaded dataset.")

csv_path = os.path.join(path, csv_files[0])

# Load dataset into Spark DataFrame
df = spark.read.csv(csv_path, header=True, inferSchema=True)

# Display Schema and Sample Data
print("Dataset Schema:")
df.printSchema()

print("\nFirst 5 Rows:")
df.show(5)

# Total Records
total_records = df.count()
print(f"\nTotal Records: {total_records}")

# Descriptive Statistics
print("\nDescriptive Statistics:")
df.describe().show()

# Check column names
print("\nAvailable Columns:")
print(df.columns)

# Retail Sales Dataset Analysis
# Replace these column names if needed after checking df.columns
category_col = "Product Category"
sales_col = "Total Amount"

print("\nCategory-wise Analysis:")
category_analysis = df.groupBy(category_col).agg(
    count("*").alias("Total_Count"),
    avg(sales_col).alias("Average_Sales"),
    max(sales_col).alias("Maximum_Sales"),
    min(sales_col).alias("Minimum_Sales"),
    sum(sales_col).alias("Total_Sales")
)

category_analysis.show()

# Top Categories by Total Sales
print("\nTop Categories by Total Sales:")
category_analysis.orderBy(desc("Total_Sales")).show(10)

# Insights
print("\nInsights:")
print(f"1. Total records processed: {total_records}")
print("2. Category-wise sales analysis completed.")
print("3. Average, maximum, minimum and total sales calculated.")
print("4. Top-performing categories identified.")
print("5. PySpark enables scalable big data processing.")

# Stop Spark Session
spark.stop()